<a href="https://colab.research.google.com/github/dima-kan/ITStep-AI/blob/superwised_learning/__pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль pandas

In [ ]:
import pandas as pd

# Інформація про дані
Зібрано дані продажу техніки в різних магазинах.
* OrderDate -- дата замовлення
* Region    -- регіон де розміщено магазин
* Manager   -- ім'я менеджера
* SalesMan  -- ім'я продавця
* Item      -- тип товару
* Units     -- кількість купленого товару
* Unit_price -- ціна за штуку
* Sale_amt   -- загальна вартість покупки

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/HalyshAnton/IT-Step-Pyton-AI/main/module2/data/sales_data.csv", index_col="Unnamed: 0")

# Завдання 1

Вивести загальну інформацію про таблицю: кількість рядків та стовпців, назви стовпців та їхній тип даних, в яких стовпцях є пропущені значення

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45 entries, 0 to 44
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderDate   43 non-null     object
 1   Region      43 non-null     object
 2   Manager     43 non-null     object
 3   SalesMan    43 non-null     object
 4   Item        43 non-null     object
 5   Units       45 non-null     float64
 6   Unit_price  45 non-null     float64
 7   Sale_amt    45 non-null     float64
dtypes: float64(3), object(5)
memory usage: 3.2+ KB

In [ ]:
df.shape

(45, 8)

In [ ]:
df.dtypes

OrderDate      object
Region         object
Manager        object
SalesMan       object
Item           object
Units         float64
Unit_price    float64
Sale_amt      float64
dtype: object

In [ ]:
df.isnull().sum()

OrderDate     2
Region        2
Manager       2
SalesMan      2
Item          2
Units         0
Unit_price    0
Sale_amt      0
dtype: int64

# Завдання 2

Перейменуйте стовпчики так, щоб назви містили літери нижнього регістру

In [ ]:
df.columns = df.columns.str.lower()

In [ ]:
df.columns

Index(['orderdate', 'region', 'manager', 'salesman', 'item', 'units',
       'unit_price', 'sale_amt'],
      dtype='object')

# Завдання 3
Виведіть дані про купівлі телевізорів та телефонів

In [ ]:
mask = (df['item'] == 'Television') | (df['item'] == 'Phone')

In [ ]:
df[mask]

,orderdate,region,manager,salesman,item,units,unit_price,sale_amt
0,2018-01-06,East,Martha,Alexander,Television,95.0,1198.0,113810.0
2,2018-02-09,Central,Hermann,Luis,Television,36.0,1198.0,43128.0
4,2018-03-15,West,Timothy,Stephen,Television,56.0,1198.0,67088.0
6,2018-04-18,Central,Martha,Steven,Television,75.0,1198.0,89850.0
7,2018-05-05,Central,Hermann,Luis,Television,90.0,1198.0,107820.0
8,2018-05-22,West,Douglas,Michael,Television,32.0,1198.0,38336.0
10,2018-06-25,Central,Hermann,Sigal,Television,90.0,1198.0,107820.0
13,2018-08-15,East,Martha,Alexander,Television,35.0,1198.0,41930.0
20,2018-12-12,Central,Douglas,John,Television,67.0,1198.0,80266.0
27,2019-04-10,Central,Martha,Steven,Television,66.0,1198.0,79068.0
29,2019-05-14,Central,Timothy,David,Television,53.0,1198.0,63494.0
36,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
39,2019-10-31,Central,Martha,Steven,Television,14.0,1198.0,16772.0

# Завдання 4
Яка загальна виручка у продавця Luis?

In [ ]:
mask = df['salesman'] == 'Luis'

np.float64(206373.0)

In [ ]:
df[mask]['sale_amt'].sum()

np.float64(206373.0)

# Завдання 5

Скільки і якого товару було продано?

див groupby(),

In [ ]:
df.groupby('item')['units'].sum()

item
Cell Phone      278.0
Desk             10.0
Home Theater    722.0
Television      716.0
Video Games     395.0
Name: units, dtype: float64

# Завдання 6
Перевірте чи правильно розраховано загальну вартість покупки. Виведіть ті рядки де є помилка. Виправте дані в таблиці

In [ ]:
df['sale_amt'] = df['units'] * df['unit_price']

In [ ]:
mask_error = df['sale_amt'] != (df['units'] * df['unit_price'])
df[mask_error]

Empty DataFrame
Columns: [orderdate, region, manager, salesman, item, units, unit_price, sale_amt]
Index: []